### PR TITLE
Add required python libraries and start the server

### LINKED ISSUE #35: Install python requirement library
**As a**  developer 
**I need** a requirements.txt 
**So that**  I could get all required libraries

**Assumptions:** 
* Python: 2.7

**Acceptance Criteria:**
When `pip install requirements.txt` is run
Then all the related libraries are installed

### PR DESCRIPTION
**Pull request by jimmyahacker**
This shall close #35 and #14

### CODE REVIEW

**Comment by jimmyahacker** [comment]
Sorry that I used one pull request to solve two issues: #35 and #14 
This is a bad manner but I was trying to speed up the progress

**Comment by Willian-Zhang** [comment]
@jimmyahacker
I'm seperating them, cuz for now, I cannot check server.py, my vagrant's still down,

**Comment by Willian-Zhang** [comment]
please check #37

**Comment by Willian-Zhang** [comment]
this was an auto merge, please start another PR @jimmyahacker

**Pull request merged**
