### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by Willian-Zhang**

### CODE REVIEW

**Comment by jimmyahacker** [comment]
I think the python version should be 2.7 instead of 3.6 in .travis.yml

**Comment by Willian-Zhang** [comment]
@jimmyahacker why?

**Comment by jimmyahacker** [comment]
@Willian-Zhang If we are to use the code template, we'd better use python 2.7

**Comment by Willian-Zhang** [comment]
@jimmyahacker by `code template` you mean the one prof. provided?
but why? is there anything not compatible?

if we use python3,
we could benefit a lot from it, such as async await keywords

**Comment by jimmyahacker** [comment]
@Willian-Zhang You are absolutely correct. I am just to make this problem simple. We could discuss later

**Comment by Willian-Zhang** [comment]
wrong procedure: call someone else to review!!!

**Pull request merged**
